rst2pdf/createpdf.py
This is the patch attached to issue #525 
Thanks in advance
=> Fix embedding of object addresses instead of dates

rst2pdf/tests/md5/test_cover.json, rst2pdf/tests/md5/test_footnotes.json, rst2pdf/tests/md5/test_issue_107.json, rst2pdf/tests/md5/test_issue_110.json, rst2pdf/tests/md5/test_issue_112.json, rst2pdf/tests/md5/test_issue_114.json, rst2pdf/tests/md5/test_issue_297.json, rst2pdf/tests/md5/test_issue_299.json, rst2pdf/tests/reference/test_cover.pdf, rst2pdf/tests/reference/test_footnotes.pdf, rst2pdf/tests/reference/test_issue_107.pdf, rst2pdf/tests/reference/test_issue_110.pdf, rst2pdf/tests/reference/test_issue_112.pdf, rst2pdf/tests/reference/test_issue_114.pdf, rst2pdf/tests/reference/test_issue_297.pdf, rst2pdf/tests/reference/test_issue_299.pdf
This should get the number of failing tests to **247**.
Related: #621.
=> Add more updated MD5s and reference tests

rst2pdf/flowables.py, rst2pdf/tests/input/textannotation.txt, rst2pdf/tests/md5/textannotation.json, rst2pdf/tests/reference/textannotation.pdf, rst2pdf/utils.py
Support PDF annotations via the TextAnnotation raw directive in this format:
.. raw:: pdf
TextAnnotation "My content here"
This is useful for speaker notes in Présentation.
=> Support text annotations

rst2pdf/tests/input/test_extensions.py, rst2pdf/tests/input/test_extensions.txt, rst2pdf/tests/md5/test_cover_2.json, rst2pdf/tests/md5/test_cover_3.json, rst2pdf/tests/md5/test_dict_styles.json, rst2pdf/tests/md5/test_extensions.json, rst2pdf/tests/md5/test_table_classes.json, rst2pdf/tests/reference/test_cover_2.pdf, rst2pdf/tests/reference/test_cover_3.pdf, rst2pdf/tests/reference/test_dict_styles.pdf, rst2pdf/tests/reference/test_extensions.pdf, rst2pdf/tests/reference/test_table_classes.pdf
Should takes us down to 207 failures.
=> Some more test updates

doc/manual.rst
Sorry, it's really minor, but I notice it every time I open this document!
=> Fix a typo and add some formatting

doc/manual.rst
Inspired by Lorna's PR (as I spotted another typo in that fragment), I have fixed all the other typos I could find the manual.
=> Spelling fixes in manual

ISSUE_TEMPLATE.md
Fixes #649 
@akrabat Is it what you expected?
=> Added the Issue Template

rst2pdf/extensions/dotted_toc.py
Fixes #719
A flake8 static code check would catch most of these.
=> Add missing import (Fix #719)

rst2pdf/extensions/fancytitles.py, rst2pdf/extensions/inkscape_r2p.py, rst2pdf/extensions/plantuml.py, rst2pdf/tests/autotest.py, rst2pdf/tests/migrate_checksums.py, rst2pdf/tests/test.py
Fixes a few issues reported by flake8, as in #724. Not all, not a lot, but some :-)
=> Some code cleanups

rst2pdf/basenodehandler.py, rst2pdf/styles.py
I will keep these coming if that's ok, because:
* They are easy to do
* They do improve the code, specially the removal of 'import *' helps static analysis tools work properly
* They slowly make running static analysis tools on the whole codebase practical
=> More cleanups

rst2pdf/sectnumlinks.py, rst2pdf/styles.py, rst2pdf/svgimage.py, rst2pdf/utils.py
Cleaned up two files, removed some code that was not used anywhere, fixed whitespace, cleaned up imports.
=> More cleanups!

doc/manual.rst
As of #747
reportlab also already supports gradient, but svglib doesn’t yet:
- https://github.com/deeplook/svglib/issues/50
- https://github.com/deeplook/svglib/issues/142
=> Docs: We use svglib

CHANGES.rst, rst2pdf/image.py, rst2pdf/opt_imports.py, setup.py
=> Removed support for PythonMagick and GFX

CHANGES.rst, rst2pdf/createpdf.py, rst2pdf/opt_imports.py
Just deleted a few lines to remove optional psyco usage
=> no more psyco

rst2pdf/extensions/vectorpdf_r2p.py, rst2pdf/image.py, rst2pdf/opt_imports.py, rst2pdf/svgimage.py
Remove LazyImports class.
Yet another step in my quest to make rst2pdf's codebase less weird :-)
=> Remove lazy imports

CHANGES.rst
Missed adding this to PR #807…
=> Update CHANGES for #807

CHANGES.rst, doc/RELEASE_PROCESS.rst
* Update CHANGES.rst for 0.98 release
=> Prepare for 0.98 release

doc/manual.rst
We recently had a question about making a table of contents and I struggled to find the docs myself so this PR adds some useful links to the manual.
=> Add some rst-specific resources to the manual

rst2pdf/flowables.py, rst2pdf/genelements.py, rst2pdf/styles/styles.style, rst2pdf/tests/input/test_separations.style, rst2pdf/tests/input/test_separations.txt, rst2pdf/tests/reference/test_separations.pdf
Add style support for separations.
Add color for separations.
=> Make separations better.

rst2pdf/tests/reference/sphinx-footnotes-order.pdf
Missed this from #965 , sorry!
=> Add reference PDF for sphinx footnotes test

rst2pdf/tests/input/test_issue_68_explicit_leading_break_with_inferred_from_fontsize_1.rst, rst2pdf/tests/input/test_issue_68_explicit_leading_break_with_inferred_from_fontsize_2.rst, rst2pdf/tests/reference/test_issue_68_explicit_leading_break_with_inferred_from_fontsize_1.pdf, rst2pdf/tests/reference/test_issue_68_explicit_leading_break_with_inferred_from_fontsize_2.pdf
I spotted this typo when watching the video of Rob's stream from yesterday morning, and thought that I'd submit a PR to fix it.
=> Fix 'whould' typo in test and reference files

doc/manual.rst
Add information to the manual about the key changes to the default stylesheet that will affect derived stylesheets. Also document how to use the old default for legacy documents.
This is the minimal requirement to address #1010.
=> Document new default stylesheet

doc/manual.rst, rst2pdf/tests/input/blue_text.yaml, rst2pdf/tests/input/green_text.yaml, rst2pdf/tests/input/red_text.yaml, rst2pdf/tests/input/test_multiple_stylesheet_files.cli, rst2pdf/tests/input/test_multiple_stylesheet_files.rst, rst2pdf/tests/reference/test_multiple_stylesheet_files.pdf
Add a test to show how multiple style sheet files works and also add this information to  the manual, though I suspect that the wording can be improved.
Attempts to address @lornajane's [comments on #1048](https://github.com/rst2pdf/rst2pdf/pull/1048#pullrequestreview-842275532).
=> Multiple stylesheet files test and update to manual 

CHANGES.rst
This change should be noted so that people can find it more easily.
=> Add information about twoColumn style to CHANGES

.github/workflows/ci.yml, .pre-commit-config.yaml, CONTRIBUTING.rst, README.rst, requirements.txt, rst2pdf/tests/conftest.py, setup.py
Updated requirements list from setup.py, since we have a few dependencies that should be patched.
=> Recompile requirements since we have a few dependabot patches open

doc/manual.rst
=> Fix type: lsit -> list

CONTRIBUTING.rst
Sometimes we may want to run the pre-commit command manually, so let's document it.
=> Document running pre-commit command manually

CHANGES.rst
If I had been smart, I would have added to #1253, before I merged it…
=> Update CHANGES to note smartypants removal
