rst2pdf/rst2pdf

gui/codeeditor.py, gui/main.py, rst2pdf/createpdf.py, rst2pdf/extensions/inkscape_r2p.py, rst2pdf/extensions/plantuml.py, rst2pdf/extensions/preprocess_r2p.py, rst2pdf/findfonts.py, rst2pdf/languages.py, rst2pdf/pdfbuilder.py, rst2pdf/sphinxnodes.py, rst2pdf/styles.py, rst2pdf/tenjin.py, rst2pdf/tests/execmgr.py
The ```except Exception, val``` syntax is not supported in python 3. A small bite in #537
=> [FIX] Python2-only except clauses

rst2pdf/utils.py
Newer xhtml2pdf versions do not depend on PyPDF, rather, it uses the newer
PyPDF2. Therefore, importing that module from xhtml2pdf will fail. In such
cases, it makes sense to look for the newer package before giving up.
=> Fix PyPDF import

rst2pdf/pdfbuilder.py
Cherry pick of the fix for #566 that is in PR #576 by @KonstantinShemyak
Sphinx changed internal representation of BuildEnvironment.indexentries in
version 1.4 (commit e6a5a3a92e938fcd75866b4227db9e0524d58f7c) by adding one
more value to the list. Update pdfbuilder accordingly to work with both
pre-1.4 and later Sphinx versions.
Closes issue #566.
=> Create document index also with Sphinx >= 1.4

rst2pdf/math_directive.py, rst2pdf/sphinxnodes.py
Added double quotes to all unquoted attribute values for `<img>` tags. This should solve issue https://github.com/rst2pdf/rst2pdf/issues/517.
=> Used quoted attributes for <img>

rst2pdf/config.py
http://python-future.org/compatible_idioms.html#configparser
```python
from ConfigParser import ConfigParser
from configparser import ConfigParser
```
Note that, as of v0.16.0, python-future no longer includes an alias for the configparser module because a full backport exists (see https://pypi.python.org/pypi/configparser).
=> Fix configparser use for Python2

doc/manual.txt, rst2pdf/pygments_code_block_directive.py, rst2pdf/styles/styles.style, rst2pdf/tests/input/test_hl_lines.txt, rst2pdf/tests/md5/test_hl_lines.json, rst2pdf/tests/reference/test_hl_lines.pdf
As we can't do background colours over whitespace, we dim the lines
that are not highlighted with the new class `pygments_diml`.
=> Support :hl_lines: code directive

CODE_OF_CONDUCT.rst
Suggested code of conduct for rst2pdf based on the PSF's Community Code of Conduct.
If anyone else wishes to be added to the list of people who get an email that's been sent to maintainers@rst2pf.org, please let me know.
Closes #622
=> Add code of conduct

doc/DEVELOPERS.txt
Adding a little context of what the tests actually do, and instructions for running one test.
Also: to mark a test as skipped, create `rst2pdf/tests/input/[test].ignore` file (which can be empty).  I couldn't find that documented anywhere and it might be handy!
=> Minor additions to testing instructions

rst2pdf/pdfbuilder.py
Since Sphinx-1.3, it expects the extensions to return its metadata on setting up.
http://www.sphinx-doc.org/en/stable/extdev/index.html#extension-metadata
At this moment, Sphinx guesses the metadata of rst2pdf.
But we're planning to drop this special treatment in nearly future (see https://github.com/sphinx-doc/sphinx/pull/4463).
This PR modifies pdfbuilder to follow the protocol for Sphinx extensions.
=> pdfbuilder does not return extension metdata for Sphinx

rst2pdf/pdfbuilder.py
I ran into this error when generating a PDF through Sphinx:
```
Running Sphinx v1.5.6
Exception occurred:
File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 512, in setup_extension
mod = __import__(extension, None, None, ['setup'])
File "/usr/local/lib/python2.7/dist-packages/rst2pdf/pdfbuilder.py", line 916
'parallel_read_safe': True,
^
SyntaxError: invalid syntax
```
It appears to be due to a typo in line 915. The change in this PR fixed the error for me.
=> Fixing typo in pdfbuilder's returned dict

doc/manual.rst
Just noticed I couldn't see the `TextAnnotation` example properly and it's a tiny typo so here's a fix :)
=> Tiny syntax fix for a command that doesn't render in the docs

doc/DEVELOPERS.rst
I tidied up the developers instructions while I was using them, this is mostly formatting fixes but I've also updated the CI information and changed the instructions from SVN to git - all as separate commits just in case it isn't helpful to have all of these changes.
=> Minor updates to the developer docs

doc/manual.rst
With this change, I'm able to compile the manual PDF
=> Update manual to point to new filenames

rst2pdf/tests/autotest.py, rst2pdf/tests/input/test_issue_239.ignore, rst2pdf/tests/input/test_issue_255_2.ignore, rst2pdf/tests/input/test_issue_390.ignore
Add messages to the `.ignore` files to explain why the test is ignored.
Also introduce the `-I` (`--ignore_ignorefiles`) switch to `autotest.py` to allow testing an ignored tes.
=> [WIP] Update ignore files

.gitignore, gui/codeeditor.py, gui/main.py, rst2pdf/createpdf.py, rst2pdf/extensions/inkscape_r2p.py, rst2pdf/extensions/plantuml.py, rst2pdf/extensions/preprocess_r2p.py, rst2pdf/findfonts.py, rst2pdf/languages.py, rst2pdf/pdfbuilder.py, rst2pdf/sphinxnodes.py, rst2pdf/styles.py, rst2pdf/tenjin.py, rst2pdf/tests/execmgr.py, setup.py
* Make except statements py3-compatible 
* Fail to run setup.py at all if py3 is used.
=> Make exceptions py3 ready

setup.py
Many people report here bugs which are python2->pytho3
related, this should help reducing the number of people
who get disappointed by the fact the project fails to run
with python3.
Even though the setup has already a check for this, adding
this classifiers also whould point this in Pypi in case a 0.94
release happens.
So this should stay until the project migration is done.
=> :Specify that this is *still* only a Python 2 project

rst2pdf/pdfbuilder.py, rst2pdf/tests/input/sphinx-issue183/conf.py, rst2pdf/tests/input/sphinx-issue229/source/conf.py, rst2pdf/tests/input/sphinx-issue254/conf.py, rst2pdf/tests/input/sphinx-issue257/conf.py, rst2pdf/tests/input/sphinx-issue285/conf.py, rst2pdf/tests/input/sphinx-issue318/conf.py, rst2pdf/tests/input/sphinx-issue319/conf.py, rst2pdf/tests/input/sphinx-issue320/conf.py, rst2pdf/tests/input/sphinx-issue360/source/conf.py, rst2pdf/tests/input/sphinx-issue364/conf.py, rst2pdf/tests/input/sphinx-issue367/source/conf.py
Sphinx has a `today` setting that should be used instead of the current
date if it exists. Use this for the date on the cover page.
This has the useful side-effect of making it possible to use a cover page in the tests too!
=> Honour the Sphinx today config setting

doc/DEVELOPERS.rst, rst2pdf/tests/test.py
When running `nosetests` with the `-v` switch, display the reason that a test was skipped by reading it from the `.ignore` file.
=> Display the reason why a test was skipped

rst2pdf/pygments_code_block_directive.py, rst2pdf/tests/input/test_issue_310.txt, rst2pdf/tests/md5/test_issue_310.json, rst2pdf/tests/reference/test_issue_310.pdf
In test_issue_310, the line numbers for the :start-at: test when using :linenos_offset: are off by one.
Addresses one of the problems with #662.
=> Fix start-at line numbers

rst2pdf/pygments_code_block_directive.py, rst2pdf/tests/input/test_issue_310.ignore, rst2pdf/tests/md5/test_issue_310.json, rst2pdf/tests/reference/test_issue_310.pdf
In test_issue_310, the line numbers for the :start-after: test when using :linenos_offset: are off by one if you the start-after text is in the middle of a line as you can see here:
I have fixed this by applying the same approach to start-after that #410 does to start-at.
Issue #410, which moved the start point to the start of the line when using `start-at`, and I think that we should move the start point to the start of the next line when using `start-after` as starting half-way through a line is weird!
The result now looks like:
Anyone disagree?
This is the second fix for #662.
=> Fix start-after line numbers

rst2pdf/createpdf.py
Release the input file handle if we opened it. 
Rationale from #592:
> I'm using rst2pdf from python code (a fabric task) and using a temporary file as an input file to add substitution variables. The problem I have is that rst2pdf.createpdf.main does not release the handler to this input file, and therefore my code cannot delete the temporary file after the pdf has been created. As there is no way to retrieve that file handler the only way to solve that is to release it from within createpdf.main.
Builds on #592 by rebasing and only closing the handler if we opened it.
=> Release input file handle

.gitignore
If you're using pyenv, you can set the python version/virtualenv that
you want to use while developing in .python-version, so this is a good
file to ignore.
=> Ignore .python-version

rst2pdf/tests/md5/test_fancytitles.json
This was the only failing test on my system and I was missing a canberra module of some kind. The output is visually identical to what I find in the references directory so I think this hash should be acceptable, the new dependency may well be causing the different hash.
=> New hash for fancytitles test

.gitignore, CHANGES.rst, README.rst, doc/RELEASE_PROCESS.rst, doc/assets/cover.tmpl, doc/assets/manual.css, doc/manual.rst, requirements.in, requirements.txt, rst2pdf/extensions/dotted_toc.py, rst2pdf/tests/execmgr.py, rst2pdf/tests/htmllog.py, rst2pdf/tests/parselogs.py, rst2pdf/tests/setmd5.py, rst2pdf/tests/zinspector12.py, setup.cfg, setup.py
Updates for releasing rst2pdf 0.94.
I've set up a test at https://test.pypi.org/project/rst2pdf
You can test the version on _Test PyPI_ using: 
```
$ pip install --index-url https://test.pypi.org/simple/ \
--extra-index-url https://pypi.org/simple rst2pdf
```
Items complete:
* Improved _long_description_ so that's it's more friendly on PyPI
* Remove `tag_svn_revision` as it's obsolete
* Added _six_ and _smartypants_ as dependencies in `setup.py` so that it works in a clean Python environment
* Remove Pillow dependency as it's provided by ReportLab now
* Updated `requirements.in` & `requirements.txt`
* Updated the project's url to rst2pdf.org
* Updated setup.py's author and author email to be generic as it must be a valid email when creating a dist file
* Updated the version number - the …
=> Prepare for 0.94

CODE_OF_CONDUCT.md
It turns out that GitHub doesn't recognise that the project doesn't have a CoC unless it's named `CODE_OF_CONDUCT.md`…
=> Convert Code of Conduct to Markdown

doc/assets/cover.tmpl, doc/manual.rst, setup.py
This will help us understand whether a bug report is from a pip install
or from latest source.
i.e. after this change, the latest source version will be:
```
$ rst2pdf --version
0.95.dev0
```
=> Update version to 0.95.dev

rst2pdf/findfonts.py
If the output of fc-match contains any unicode characters, then we need to handle this in Python 2.
Fixes #757
=> Decode output of fc-match in Python2 as UTF-8

rst2pdf/createpdf.py, rst2pdf/pdfbuilder.py
Passing in a complete Windows path made jinja2 raise a `TemplateNotFound` exception.  This is because "[t]emplate paths are not necessarily filesystem paths and thus always use forward slashes."
=> Fixes #766: Delegate finding cover template to jinja2.

rst2pdf/flowables.py
**Describe the bug**
When running html generation I ended up with the error:
```
Exception occurred:
File "/usr/local/lib/python2.7/dist-packages/rst2pdf/flowables.py", line 895, in <module>
if reportlab.Version == '2.1':
NameError: name 'reportlab' is not defined
```
**To Reproduce**
Steps to reproduce the behavior:
```
sphinx-build -b html -d stage/doctrees   source/welcome stage/html
```
=> Fixed reportlab import

rst2pdf/flowables.py
This fixes #771 for 0.94.x as it's breaking on latest ReportLab and will allow us to release 0.94.1 with just this fix in it.
I've also created a `0.94.x` branch from the `0.94` tag in order to give us somewhere to release 0.94.1 from.
=> Import reportlab into flowables.py

CHANGES.rst, rst2pdf/flowables.py, rst2pdf/genelements.py
Prior to ReportLab 3.5.19, a link that wasn't well-formed was assumed to
be an internal anchor. This was [fixed][1] in 3.5.19, so we now need to
prefix all internal links we generate with `#`.
This fixes #772 
[1]: https://bitbucket.org/rptlab/reportlab/commits/c46115a85b61f4822026e72f5949a4fb1b63ba73
Given `test.rst`:
```rst
===============================
Document with Table of Contents
===============================
.. contents:: Table of Contents
:depth: 2
Heading 1
=========
Normal, **Bold**, *Italic*.
This is a paragraph in Page 1 [#]_
.. [#] This is a footnote in page 1
```
Run:
```
rst2pdf test.rst
```
Open the resulting `test.pdf` and resize into a vertically narrow window and ensure that 
* The TOC link takes you to the _Heading 1_ section 
* The footnote at the end of the …
=> Fix internal links so that they work with latest ReportLab

CHANGES.rst, rst2pdf/image.py, rst2pdf/tests/md5/test_fancytitles.json
Resolves https://github.com/rst2pdf/rst2pdf/issues/780 and a new svg-related issue.
I followed the same six-related pattern found throughout createpdf.py, genpdftext.py, and pdfbuilder.py.
SVG image support is currently optional. By importing the svgimage module at the top of the image.py module, any rst document that contained an image relied on having svglib installed, whether or not that image were an svg. This PR fixes that problem. :tada:
=> Fix image retrieval over urlretrieve + svg import errors

rst2pdf/pdfbuilder.py
This function was deprecated in sphinx 1.6 and removed in 2.0. The
function call is replaced with the recommended replacement according to
https://www.sphinx-doc.org/en/stable/extdev/index.html
Signed-off-by: Sven Schwermer <sven.schwermer@disruptive-technologies.com>
=> Replace deprecated BuildEnvironment.create_index()

LICENSE.txt
Rather than list all copyright holders in the license file directly, we now reference them as the "contributors to the rst2pdf project".
The full list of contributors is available via `git shortlog -sn` or via https://github.com/rst2pdf/rst2pdf/graphs/contributors.
This addresses issue #768
=> Update LICENSE copyright to reference all contributors

rst2pdf/pdfbuilder.py
Replace Sphinx's `HighlightLanguageTransform` with our own just for Sphinx versions between 1.8.0 & less than 2.0.0 as these versions have broken the `:linenothreshold:` setting in the `highlight` directive.
This code can be removed when we drop support for Python 2
Fixes #721
=> Fix highlight's linenothreshold for Sphinx >=1.8+ & <2.0

rst2pdf/image.py
Unless difference between Import Error and Module Not Found Error is that important for SVGImage import.
=> Make it still work with Python 2

rst2pdf/findfonts.py
This was enough to make pdfbuilder work with Sphinx 2.2.0 in Windows 10.
Fixes #806
=> Fix for fonts in Windows

CHANGES.rst, rst2pdf/pygments_code_block_directive.py, rst2pdf/tests/input/test_no_language_set_on_code_block.txt, rst2pdf/tests/md5/test_no_language_set_on_code_block.json, rst2pdf/tests/reference/test_no_language_set_on_code_block.pdf
As per the rST specification[1] allow the code-block directive's language argument to be optional.
Fixes #819
1: https://docutils.sourceforge.io/docs/ref/rst/directives.html#code
=> Allow code-block language to be optional

doc/assets/cover.tmpl, doc/manual.rst, setup.py
With 0.95 released, we update the code to 0.96.dev so that we can distinguish a bug reported against the master branch from one against the 0.95 release.
=> Update master version to 0.96.dev

doc/DEVELOPERS.rst, doc/manual.rst, rst2pdf/extensions/dotted_toc.py
The title levels in `manual.rst` are inconsistent and this is a fatal error in docutils. 
In addition, `DEVELOPERS.rst` is pulled into manual.rst, so the title levels in `DEVELOPERS.rst` need to be adjusted so that the sections within `DEVELOPERS.rst` sit within the chapter in manual.
Finally, the comment text in the extensions are also pulled into `manual.rst`, so the `dotted_toc` comment needed updating so that it didn't create a new chapter in the manual.
For reference when reviewing, the levels used by the manual are:
level 1: ============
level 2: ------------
level 3: ~~~~~~~~~~~~
level 4: ************
level 5: """"""""""""
Fixes #833
=> Fix manual

README.rst
The current links do not work.
=> Fix PyPI links in README

CHANGES.rst, setup.py
Without specifying the package_dir mapping, data belonging to the
rst2pdf package such as styles wouldn't install properly for my system.
=> Fix generation of source tarball

CHANGES.rst, requirements.txt
Addresses CVE-2019-19911 & CVE-2020-5313 as noted by Dependabot.
=> Update Pillow to 6.2.2

doc/assets/cover.tmpl, doc/manual.rst, setup.py
With 0.97 released, we update the code to 0.98.dev so that we can distinguish a bug reported against the master branch from one against the 0.97 release.
=> Update master version to 0.98.dev

rst2pdf/tests/conftest.py
If we use the latter, we see a really ugly, hard-to-parse traceback. The latter is much more subtle so use that.
The 'pytrace' variable is set to False on all values to avoid triggering a full traceback from 'pytest.fail' also [[1][1]].
[1]: https://docs.pytest.org/en/stable/reference.html#pytest-fail
=> Use 'pytest.fail' instead of 'assert' in test

CHANGES.rst, rst2pdf/extensions/inkscape_r2p.py
Per #869, inkscape 1.0 final uses '--export-filename' - not '--export-file'. This was causing test failures on Fedora 31.
While we're here, we take the opportunity to clean up this file, replacing some hardcoded paths on Windows and running the whole thing through black. We can do a lot more of the latter as we proceed with fixing various bugs and removing all the skipped tests.
=> Use correct argument to 'inkscape'

CHANGES.rst, LICENSE.txt, MANIFEST.in, doc/RELEASE_PROCESS.rst, doc/manual.rst
These files should be in the PyPI download. I've also updated the copyright year to 2020 in the license.
Fixes #866.
=> Add LICENSE, README and CHANGES to source tarball

README.rst, doc/manual.rst
- Mark some code blocks in the README as such
- Add a summary of Sphinx integration
- Remove some Python 2'isms from the manual
=> Address some doc nits

.git-blame-ignore-revs, doc/DEVELOPERS.rst
After the mass-reformatting in PR #877, it is helpful to ignore the commits that simply reformat the code when using `git blame` as it makes it more useful.
This is most easily done using a file containing the list of commits - I've called it `.git-blame-ignore-revs` - and a config setting (`git config blame.ignoreRevsFile .git-blame-ignore-revs`).
=> Add .git-blame-ignore-revs file

doc/manual.rst
The docutils classes item-list, bullet-list, option-list, field-list,
item-list-item and bullet-list-item are referred in the manual with
underlines instead of dashes, making them invalid docutils class names.
Fix those references in the manual.
=> Fix docutils class names in manual

CHANGES.rst, requirements.txt
I noticed a dependabot alert so I thought I'd add a patch for that.
=> Update Pillow to 7.1 as advised by Dependabot

rst2pdf/tests/input/sphinx-issue183/conf.py, rst2pdf/tests/input/sphinx-issue229/conf.py, rst2pdf/tests/input/sphinx-issue254/conf.py, rst2pdf/tests/input/sphinx-issue257/conf.py, rst2pdf/tests/input/sphinx-issue285/conf.py, rst2pdf/tests/input/sphinx-issue318/conf.py, rst2pdf/tests/input/sphinx-issue319/conf.py, rst2pdf/tests/input/sphinx-issue320/conf.py, rst2pdf/tests/input/sphinx-issue360/conf.py, rst2pdf/tests/input/sphinx-issue364/conf.py, rst2pdf/tests/input/sphinx-issue367/conf.py
The cover page on a Sphinx test have a date on it that defaults to today's date. However, for the tests to pass we need the date to match the date on the reference PDF. This is controlled by the Sphinx setting `today` which we need to set.
This setting was inadvertently removed for this set of tests in PR #855 (commit 89c630b356d5bc40524c30b171629e6fe86e0885).
=> Restore today setting to Sphinx cover page tests

rst2pdf/rson.py
Thanks to a really excellent bug report (thanks @rswarbrick), I was able to look at the regex that triggers a FutureWarning in `rson.py` (line 119, I'm so tired of this warning!) and add a little extra escaping. I can't replicate the same warning message with this change.
=> Escape the regex to remove a FutureWarning. Fixes #880

doc/manual.rst
The fontSize attribute also permits percentage values which are relative
to the style's parent, but this behavior wasn't yet documented.
Add paragraph and example describing its usage in the "Style definition"
section of the manual.
=> Document fontSize usage with percentage values

CONTRIBUTING.rst, setup.py
Wordaxe support was removed in #887. Still, it was listed as a requirement for the `hyphenation` target in `setup.py`. Since the package wasn't able to be downloaded, the installation of the requirements failed.
Since wordaxe was the only package listed in the `hyphenation` target, and hyphenation is now handled by reportlab, remove the `hyphenation` target from `setup.py`, and also remove it from the command in CONTRIBUTING.
=> Fix requirements installation by removing wordaxe requirement

doc/manual.rst
Update the manual's Hyphenation chapter to use pyphen instead of the deprecated wordaxe. Fixes #888.
From my tests, the `-l` flag for rst2pdf didn't work for hyphenation contrarily to what the `--help` says, so I dropped the documentation text regarding that flag.
If that flag will only support setting the docutils language moving forward, I could also send a PR fixing the `--help` text for `-l`.
I also dropped the hyphenation preview for the spanish text, since it already wasn't working and I didn't see much other use of `.. class` in the manual. To get this to work would probably involve adding a style with the spanish language and lower text width and using its class here. If you think it would be a good addition I can add it to this PR.
=> doc: Document hyphenation using pyphen

rst2pdf/tests/conftest.py, rst2pdf/tests/input/test_uml_extension.depends
Add support for having a `.depends` file alongside a test, with each of its lines listing a dependency. The dependency name is indexed in the `check_dependency` dictionary, returning the method that checks if that dependency is satisfied.
If any of the dependencies listed for a test isn't satisfied, the test is skipped.
This was motivated by the `test_uml_extension`, which requires `plantuml` to be installed. In case this program wasn't present, it would cause the test to fail. Besides adding support for dependencies, this adds the `plantuml` dependency for `test_uml_extension`, so that if `plantuml` is installed it passes, otherwise it is skipped. Fixes #935.
Besides, the first commit simply fixes some Black coding style issues in the file, as the `pre-commit` git plugin wouldn't let me …
=> Add dependency check for tests

.github/workflows/ci.yml
Add an artifact-storing job to the github workflows to store all test outputs. This makes the files available as an "artifact" so we can download them and debug what happened (logs and PDFs). Retains for 8 days.
=> Store test outputs to aid debugging

CONTRIBUTING.rst
The current markdown text formatting causes the text to show incorrectly
when viewed on GitHub and causes an `Unknown target name` error if you
tried to run rst2pdf on it.
This change fixes the text to use the rst emphasis formatting and fixes
the rendering and compiling issue.
=> Fix text formatting

rst2pdf/pdfbuilder.py, rst2pdf/tests/input/sphinx-footnotes-order/conf.py, rst2pdf/tests/input/sphinx-footnotes-order/index.rst
When using rst2pdf with sphinx, if the document has footnotes and the
footnote definition appears before any of the footnote references, it
crashes with the following error:
```
[ERROR] pdfbuilder.py:159 Failed to build doc
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/rst2pdf/pdfbuilder.py", line 156, in write
docwriter.write(doctree, destination)
File "/usr/lib/python3.9/site-packages/docutils/writers/__init__.py", line 78, in write
self.translate()
File "/usr/lib/python3.9/site-packages/rst2pdf/pdfbuilder.py", line 587, in translate
self.document.walkabout(visitor)
File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 214, in walkabout
if child.walkabout(visitor):
File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 214, in walkabout
if …
```
=> Fix crash when generating footnotes out of order under sphinx

CONTRIBUTING.rst
Fix the filename (remove the additional full stop at the beginning of
the file name) and move the following word onto the line as there's more
room now.
=> Fix filename for .git-blame-ignore-revs

rst2pdf/genpdftext.py, rst2pdf/tests/input/test_embedded_reference.rst, rst2pdf/tests/reference/test_embedded_reference.pdf
A reference with another reference as its embedded URI yields a target
with either 'refid' or 'refuri' set, depending on whether it points to a
section or an URL, respectively.
Previously it was always assumed to have 'refuri', causing rst2pdf to
crash when the embedded reference was a section. To fix the issue, use
either 'refid' or 'refuri' as the anchor 'name' field, depending on
which is present in the target node.
=> Fix #820: Use right anchor name for target nodes

requirements.in, requirements.txt, setup.py
#956 moved stylesheets to yaml, but didn't add `pyyaml` as a requirement. Add it.
This is done on top of #969, since my environment is on python 3.9 and I need it to test the change, and also because when generating the `requirements.txt` with `pip-compile` to add `pyyaml`, it updates other packages much like in #969, so doing it on top of #969 keeps the diff small.
=> Add pyyaml to the requirements

rst2pdf/pdfbuilder.py, rst2pdf/tests/input/sphinx-versionmodified/conf.py, rst2pdf/tests/input/sphinx-versionmodified/index.rst, rst2pdf/tests/reference/sphinx-versionmodified.pdf
closes #981 
I don't know when, but there was a change to how the `versionlabels` dict was declared (& possibly changed usage also) in Sphinx. This resulted in a failure to build a pdf when using `versionadded`, `versionchanged`, and `deprecated` directives.
See #981 for problematic output and concluding solution.
This PR fixes the pdfbuilder.py to compensate for the changes in Sphinx.
=> fix versionadded & version changed directives

.github/workflows/ci.yml
We require the tests to pass under Python 3.9 now. Python 3.10 is in early dev, but we should test it, allowing it to fail - which it does!
Also only upload the test output files if they fail as we don't need them if the tests pass. It'd be neater to only upload the failed PDF and log files, but this is a good first step.
Finally, split the install dependencies step to separate the apt installation from the pip one as it makes it easier to diagnose when it fails due to fewer lines to scroll through.
=> Update CI versions and only upload assets on failure

rst2pdf/genpdftext.py, rst2pdf/tests/input/test_embedded_reference.rst, rst2pdf/tests/reference/test_embedded_reference.pdf
#820 didn't actually fix embedded references. It made rst2pdf no longer crash, but with it, using embedded references makes the links point to the wrong place. Using the test edited in this PR as an example:
There is a target on the heading on the second page:
```
.. _s2idle_resume:
```
However, with the "fix" in #820, the following reference:
```
`below <s2idle_resume_>`_
```
that should link to the heading on the second page, produces an anchor named `s2idle_resume` (`<a name="s2idle_resume">`), effectively hiding the heading's anchor and making all other links point to ``` `below <s2idle_resume_>`_ ``` instead, which is on the first page rather than the second.
In this PR, I'm using the `name` property from the node instead of `refuri` so that no longer happens. But I honestly don't …
=> Fix embedded references (again)

rst2pdf/createpdf.py
Commit c3a7c5c21 modified how we imported extension modules to add
Python 3 compatibility. Unfortunately this introduced a bug, whereby we
will no longer error out if neither of our two attempts to import the
module, by full path and by module path, succeeds.
Restore this behavior.
Closes: #920
=> createpdf: Error out when importing extension fails

rst2pdf/tests/input/sphinx-break-level-0/conf.py, rst2pdf/tests/input/sphinx-break-level-0/index.rst, rst2pdf/tests/input/sphinx-break-level-1/conf.py, rst2pdf/tests/input/sphinx-break-level-1/index.rst, rst2pdf/tests/input/sphinx-break-level-2/conf.py, rst2pdf/tests/input/sphinx-break-level-2/index.rst, rst2pdf/tests/reference/sphinx-break-level-0.pdf, rst2pdf/tests/reference/sphinx-break-level-1.pdf, rst2pdf/tests/reference/sphinx-break-level-2.pdf
This is a set of tests that show how the `pdf_break_level` option affects the same document.
As useful for documentation as for proving it works, I think but equally it could be argued that this would be better in the manual or on the website.
=> Add tests for Sphinx pdf_break_level config option

rst2pdf/createpdf.py
When ReportLab builds the PDF, hook into the onProgress callback and display progress information when using --very-verbose. This will hopefully make it a little bit easier to determine what has gone wrong.
For example when an image in a `figure` is too large you will get a "Likely that a flowable is too large for any frame" error.
This is the relevant part of the output:
```
INFO] createpdf.py:665 Starting build
[DEBUG] createpdf.py:739 Number of flowables: 6
[DEBUG] createpdf.py:747 Page 1: Flowable 1 <class 'reportlab.platypus.paragraph.Paragraph'>
[DEBUG] createpdf.py:747 Page 1: Flowable 2 <class 'reportlab.platypus.paragraph.Paragraph'>
[DEBUG] createpdf.py:747 Page 1: Flowable 3 <class 'rst2pdf.flowables.MySpacer'>
[DEBUG] createpdf.py:747 Page 1: Flowable 4 <class …
```
=> Add more progress information to --very-verbose

.github/workflows/ci.yml, requirements.3.6.txt, requirements.3.7.txt, rst2pdf/tests/conftest.py
Add Python 3.10 to the CI matrix.
Update dependencies specified in requirements.3.x.txt. We can continue to use the 3.7 requirements for 3.8, 3.9 & 3.10.
=> Add Python 3.10 to CI & update dependencies

doc/manual.rst, rst2pdf/basenodehandler.py, rst2pdf/tests/input/test_multiple_styles.rst, rst2pdf/tests/input/test_multiple_styles.yaml, rst2pdf/tests/reference/test_multiple_styles.pdf
For each style after the first one listed, apply the attributes that are different from the defaults to the compbined style. This results in a style that's the combination of all the listed styles.
This has been  long-standing wish list item for myself!
Addresses #1035
=> Support multiple style names for the `class` directive

rst2pdf/math_flowable.py
A critical warning appears during the build of the documents for each char inside the math formula even if it correctly appears in the pdf since the math support is not yet complete in rst2pdf,. For this reason, the log.critical() lines that generate them are being remove from math_flowable.py.
Signed-off-by: Arianna Galzerano <ariannagalzerano@gmail.com>
Closes: #1080
=> math_flowable: remove unnecessary critical warining

doc/rst2pdf.rst, rst2pdf/createpdf.py, rst2pdf/styles.py, rst2pdf/utils.py
Add new parameter --record-dependencies which works the same way was for vanilla docutils rst2foo commands.
The target file will contain a list of files that were used to generate the output file. The list can be consumed by build-systems to efficiently regenerate the PDF if any of the inputs has changed.
Fixes #1108
=> Write dependency file

rst2pdf/createpdf.py, rst2pdf/utils.py, tests/reference/test_stylesheet_includes.pdf
Due to the way our CI was set up and a failure to manually run the pytest tests locally before merging, we ended up merging two PRS (#1111 and #1126) that broke the tests. This PR fixes both.
For #1126, `test_stylesheet_includes` is now a two-column PDF again so we need to update the reference file.
For #1111, recording dependencies breaks Sphinx, which does't even allow this option to be set. Hence, if the `--record-dependencies` option is not set, we no longer do the recording as we're not going to use the result anyway.
=> Fix test failures

.github/workflows/ci.yml
We don't want to allow everything to `continue-on-error` as we don't spot when there's a real failure.
We let 3.11 fail as ReportLab 3.6.3 doesn't install on 3.11 and we need move to a more recent ReportLab for that one (#1110).
=> Only allow Python 3.11 builds to fail

tests/conftest.py
If a user has another language configured in ~/.rst2pdf/config, for example "language=de", some of the tests will fail. By setting "en" explicity, the same tests will pass.
The following tests fail with language="de" in the config file:
```
FAILED tests/input/test_custom_cover.rst::test_custom_cover
FAILED tests/input/test_issue_128.rst::test_issue_128
FAILED tests/input/test_issue_117.rst::test_issue_117
FAILED tests/input/test_cover.rst::test_cover
FAILED tests/input/test_cover_2.rst::test_cover_2
FAILED tests/input/test_issue_109.rst::test_issue_109
FAILED tests/input/test_issue_299.rst::test_issue_299
FAILED tests/input/test_issue_165.rst::test_issue_165
FAILED tests/input/test_issue_288.rst::test_issue_288
FAILED tests/input/test_issue_64_handle_multiple_authors_in_metadata.rst::test_ …
```
=> Set language to "en" when running tests.

.gitignore, doc/RELEASE_PROCESS.rst
A few minor changes for clarity to make it easier next time. Also add `/build` to `.gitignore` as it's created when building the release artifacts.
=> Update release process document

rst2pdf/createpdf.py, rst2pdf/genelements.py
This PR reorders the caller arguments according to the parameter list of the class to minimize mental debt when studying the code (see #1146). No functional change. Tests pass.
=> Reorder caller args as discussed in #1146

rst2pdf/config.py
Py 3.12 finally pulled the plug on the `SafeConfigParser` class which has been deprecated since py 3.2. Use `ConfigParser` as the recommended replacement.
=> Adjust to py 3.12

README.rst, doc/DEVELOPERS.rst
With the adoption of PEP 668, installation of applications such as rst2pdf with pip is discouraged and pipx is a better choice. Update our instructions to use pipx. 
I also removed the Travis badge and renamed `master` to `main` in the README.
Finally, I've improved DEVELOPERS.rst to provide more comprehensive instructions for setting up rst2pdf for development with a venv and tidied up some other bits so that they are
more accurate/useful.
Fixes #1165
=> Update installation instructions for pipx (and other tidy-ups)

rst2pdf/styles/twocolumn.yaml, tests/reference/test_stylesheet_includes.pdf
This file is required as a way to set the two column layout via a stylesheet. It was incorrectly removed in #1126.
Fixes #1159
=> Restore twocolumn.yaml

doc/manual.rst
The manual's examples for embedded fonts are now copy/paste-able into a style file. I've also updated the font font names to the new ones.
=> Update embedded fonts section in  manual

rst2pdf/basenodehandler.py, rst2pdf/directives/code_block.py, tests/input/test_hl_lines.rst, tests/reference/test_hl_lines.pdf
As plain text code blocks have a different path through the codeblock directive, we need to apply the hl_lines "`diml`" class in this section too in order for highlighting to work.
I've also improved the Python test to show that syntax highlighting works on the highlighted lines and updated an error message to show the name of a class rather than its index within the list of classes.
This is an example from the new test in this PR:
RST code:
```rst
.. code-block:: text
:linenos:
:hl_lines: 2
To be
or not to be
that is the question
```
Before this PR, only the first line number is dimmed:
After, it works as you'd reasonably expect:
=> Make the hl_lines directive work with plain text

rst2pdf/pdfbuilder.py
According to the Sphinx documentation Builders should include an attribute `supported_image_types`, that lists which images types can be used by this builder.
https://www.sphinx-doc.org/en/master/extdev/builderapi.html#sphinx.builders.Builder
Other plugins rely on this behavior.
By specifying the list of image types, we ensure that the API exposes the capabilities correclty (since rst2pdf has image support).
=> pdfbuilder: Add supported_image_types attribute

doc/manual.rst, rst2pdf/pdfbuilder.py, tests/input/sphinx-subtitle-prefix/conf.py, tests/input/sphinx-subtitle-prefix/index.rst, tests/reference/sphinx-subtitle-prefix.pdf
I think that the end user should have the option to change the default subtitle prefix. For example, from "version" to "release" or "v.". It would also allow the end user to set the prefix to a empty string to remove it completely when not needed.
=> Add config option to change default subtitle prefix

.github/workflows/ci.yml, tests/input/sphinx-subtitle-prefix/conf.py
The `sphinx-subtitle-prefix` test has been failing due to a date issue. This PR fixes it by setting the date to match the reference PDF.
However, this was not found earlier because the CI indicates that the workflow passed even though it didn't. This is due to `continue-on-error: true` that we thought we needed to make the artefact upload step work. However, we subsequently changed the artefact upload step to upload only on failure by adding `if: failure()`, which I believe achieves what we were trying to do with `continue-on-error: true`.  However, we didn't update the pytest step, so this PR removes the `continue-on-error: true` now so that a failure is recognised by the system.
=> Fix sphinx subtitle prefix test and ensure CI fails on test failures

tests/conftest.py
PyMuPDF might be available on a system as fitz_old, which is currently the case for Debian sid. Try to import it if import fitz fails.
=> Deal with PyMuPDF installed as fitz_old

.github/workflows/ci.yml, requirements.txt, rst2pdf/findfonts.py
We're not testing against the newest versions of Python, this adds them to the CI build matrix so we can check what's what.
=> Update the python versions we use in CI to include 3.12 and 3.13 (experimental)

tests/conftest.py
While working on my second PR for #738, I noticed that the sample test command in `doc/DEVELOPERS.rst` no longer works:
> Running a single test
> *********************
> 
> To run one test only, simply pass the file or directory to pytest. For example::
> 
>   pytest tests/input/sphinx-repeat-table-rows
Local result:
```
 $  uv run pytest tests/input/sphinx-repeat-table-rows
================================ test session starts =================================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/kyle/repos/rst2pdf
configfile: pyproject.toml
plugins: xdist-3.6.1
collected 0 items
=============================== no tests ran in 0.04s ================================
```
After some digging, I found it was because the custom test collection logic used …
=> Fix sphinx test collection logic

doc/manual.rst
In trying to [update the documentation for the project](https://github.com/rst2pdf/rst2pdf.github.io/pull/38), there's a lot of things in the manual that are duplicated from the publicly available source, or reproduced in the manual which doesn't feel appropriate (maybe just outdated!). This pull request switches the long contribution file, copied CLI help output and extension comments for some words and links to the original sources.
=> Refresh manual, remove external docs content

rst2pdf/directives/code_block.py, tests/input/test_emphasize_lines.rst, tests/reference/test_emphasize_lines.pdf
Fixes #1057 to add support for `emphasize-lines` (note the hyphen!) for code blocks because Sphinx does. We usually use `hl_lines` because that's how it's named in Pygments.
With this change, both versions are supported, so that using `emphasize-lines` will render with either tool.
NOTE: if syntax highlighting is broken, or the dimming doesn't work, the tests don't fail. I think the colour changes aren't severe enough. I did add a test but I'm not confident it would catch a regression on this option name. Suggestions welcome!
=> Support emphasize-lines as an alias for hl_lines

pyproject.toml
As per https://setuptools-scm.readthedocs.io/en/latest/usage/, we need the `[tool.setuptools_scm]` table in `pyproject.toml` to enable setuptools-scm.
=> Add section for setuptools_scm in pyproject.toml

doc/RELEASE_PROCESS.rst, pyproject.toml
To ensure that the correct version number is applied when building for release and also on the manual's cover page, we have to do some work with uv. 
This is because uv stores the version number of rst2pdf in uv.lock itself. To get the version number in the lock file to match the tag we need to:
1. Checkout a clean `main`
2. Create a tag
3. Run `uv lock`
4. As this has updated the `uv.lock` file, we need to commit this changed file
5. Move the tag to the new commit so that uv.lock's version matches the tag.
6. Push `main` and the tag to GitHub
There's a minor problem here in that the person doing this work needs the right to push to main, so I imagine we'll need to revisit this at some point. Maybe when we automate it!
This PR:
1. Updates pyproject.toml to so that `uv` will rebuild when …
=> Support dynamic versions for releasing with uv

pyproject.toml
Set license-files to an empty array to work around issues releasing to PyPI. See:
- https://github.com/astral-sh/uv/issues/9513
- https://github.com/pypa/setuptools/issues/4759
=> Workaround pypa/setuptools#4759

pyproject.toml
Needed to show the 3.13 badge on PyPI.
=> Add Python 3.13 classifier to pyproject.toml

pyproject.toml, rst2pdf/basenodehandler.py, rst2pdf/createpdf.py, tests/input/sphinx-smartquotes/index.rst, tests/input/test_smarty.rst, tests/reference/sphinx-smartquotes.pdf, tests/reference/test_smarty.pdf, uv.lock
Fixes #1244 where we depend on smartypants but it's no longer actively maintained and has problems with newer versions of Python.
Looks like Sphinx or docutils ran into this and wrote the replacement function we need (I love open source) but something funky is going on - the same configuration options are supported as in our manual, but the output isn't quite right and two of the tests fail so I need to take another look before we can properly review//merge.
=> Remove smartypants, use the docutils version

.github/CODEOWNERS
We don't have reviewers by default (although the maintainers are subscribed to notifications). Adding ourselves as codeowners so we'll get tagged for review.
=> Add codeowners to tag reviewers on every PR

README.rst
The other location was dead. Although rst2pdf.org points to a new PDF file (https://rst2pdf.org/_downloads/cb7dadec71e04885ee6e55dec4d89d6d/manual.pdf), that one seems empty.
The HTML one linked from the home page works.
=> Link to the HTML manual

pyproject.toml, rst2pdf/__init__.py, rst2pdf/roles/package.py
I think that importlib_metadata could be removed from Debian before end of 2025, let's see how it fares.
=> drop usage of old importlib_metadata
